### PR TITLE
Add russian localy

### PR DESCRIPTION
**Pull request by bropines**
Add Ru readme and ru localy (only in the language files, in the code I can't help you add).

### CODE REVIEW

**Comment by bropines** [comment]
As a default font for Russian I suggest to put the system Segoe UI.

**Comment by Poker-sang** [comment]
Thanks for the reminder, I hadn't thought about fonts before.

**Comment by Poker-sang** [comment]
lgtm

**Review by Poker-sang — APPROVED** [review]

**Comment by Poker-sang** [comment]
I wrote a simple app that can figure out the missing resources. I hope it could help.

image

**Comment by bropines** [comment]
Convenient, can I somehow get/run it? In general, it would not be bad to add there the creation and editing of existing languages ​​based on other languages ​​(for example, I was translating from Chinese 😊).

**Comment by Poker-sang** [comment]
Edit existing language? Maybe I'll implement it later.
You can find its source code in https://github.com/Pixeval/ResourceChecker

Or you can run the published one:
[ResourceChecker.zip](https://github.com/Pixeval/Pixeval/files/14538521/ResourceChecker.zip)

**Comment by bropines** [comment]
By the way, the resource links were lost in translation
`<PRIResource Include="Strings\ru-ru\EntryContainer.resjson" />`
And I've added the translation of the function locally for now:
`<PRIResource Include="Strings\ru-ru\CheckExitedContentDialog.resjson" />`
When you're going to release a new version, tag me here (I'm subscribed to notifications and I'll update everything within a couple hours.

**Pull request merged**
