### PR TITLE
AOT部分支持

### PR DESCRIPTION
**Pull request by Poker-sang**

### CODE REVIEW

**Comment by bropines** [comment]
I know this is not the place to write, but on the last main branch, when opening “About the application” the program crashes

image

**Comment by Poker-sang** [comment]
> I know this is not the place to write, but on the last main branch, when opening “About the application” the program crashes

Thanks for heads-up, I will try-catch here

**Comment by bropines** [comment]
Also I wanted to make beautiful, even gave this block the ability to display in mardown but it is very bad for him
image

**Comment by Poker-sang** [comment]
`MarkdownBox` is still in preview/beta, so the style is not so pretty and there are a lot of bugs, maybe it's better to wait until the official release.

**Comment by bropines** [comment]
By the way, my likes stopped working. It's just that the button doesn't work. Not in the menu at the bottom, not in the pictures. Not added to favorites (I would remove the proofs, but I have a lot of 18+ content in my favorites)

**Pull request merged**
